version: '3'
services:

  db:
    image: postgres:14.3
    container_name: postgres_db
    environment:
      POSTGRES_DB: $PG_DB
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file:
      - .env
    restart: always

  django:
    build: kenki228/cinema_django
    env_file: .env
    volumes:
      - ./django_logs:/app/logs
      - static:/app/data/static
      - media:/app/data/media
    expose:
      - "8000"
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - static:/static
      - media:/media
    depends_on:
      - django
    ports:
      - "80:80"

  etl:
    build: kenki228/cinema_etl
    volumes:
      - etl_data:/src/data
    env_file:
      - .env
    depends_on:
      - db
      - elastic
    restart: always

  fastapi:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - elastic
    expose:
      - "8001"
    restart: always

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - 'xpack.security.enabled=false'
      - "discovery.type=single-node"
    expose:
      - "9200"
    restart: always

volumes:
  static:
  media:
  etl_data:
  db_data: